#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────
# bootstrap-hermes-config.sh
#
# Idempotent first-run bootstrap for the Hermes agent's config.yaml.
#
# - Runs on the VPS during deploy, wrapped in `doppler run` so secrets are
#   injected from Doppler (DASHBOARD_USERNAME / DASHBOARD_PASSWORD).
# - Hermes state lives in a named Docker volume (mounted at /opt/data), NOT
#   a host folder — so this script reads/writes config.yaml through a
#   throwaway helper container that mounts that volume.
# - If config.yaml already exists and is valid (`_config_version` present),
#   it is left completely alone — the dashboard owns it from then on.
# - Otherwise it writes a minimal valid config (dashboard basic auth +
#   `_config_version: 12`), so the dashboard can start on first boot with
#   zero manual SSH. No `hermes setup` wizard required.
#
# Secrets used (from Doppler):
#   DASHBOARD_USERNAME     (default: admin)
#   DASHBOARD_PASSWORD     (required — used to derive the auth hash)
#   DASHBOARD_PUBLIC_URL   (required for public access; optional if only local access is needed)
# ─────────────────────────────────────────────────────────────────────────

set -euo pipefail

HERMES_VOLUME="${1:?usage: bootstrap-hermes-config.sh <hermes-volume>}"
IMAGE="nousresearch/hermes-agent:latest"
MOUNT="/opt/data"

DASH_USERNAME="${DASHBOARD_USERNAME:-admin}"
DASH_PASSWORD="${DASHBOARD_PASSWORD:-}"
PUBLIC_URL="${DASHBOARD_PUBLIC_URL:-}"

# Already provisioned? Never touch it — the dashboard owns config from here.
if docker run --rm \
  -v "$HERMES_VOLUME:$MOUNT" \
  --entrypoint /bin/sh \
  "$IMAGE" -c '[ -f /opt/data/config.yaml ] && grep -q _config_version /opt/data/config.yaml'; then
  echo "[bootstrap] $HERMES_VOLUME:/opt/data/config.yaml already provisioned — leaving untouched."
  exit 0
fi

if [ -z "$DASH_PASSWORD" ]; then
  echo "[bootstrap] ERROR: DASHBOARD_PASSWORD is not set in Doppler. Cannot configure dashboard auth." >&2
  exit 1
fi

# Preserve any existing (e.g. stale pre-v12) config for reference.
if docker run --rm -v "$HERMES_VOLUME:$MOUNT" --entrypoint /bin/sh "$IMAGE" \
  -c '[ -f /opt/data/config.yaml ]'; then
  echo "[bootstrap] Backing up existing config inside the volume…"
  docker run --rm -v "$HERMES_VOLUME:$MOUNT" --entrypoint /bin/sh "$IMAGE" \
    -c 'cp /opt/data/config.yaml "/opt/data/config.yaml.bak-$(date +%s)"'
fi

# Derive the auth hash using the Hermes image's own helper.
# The password travels via env, never on the command line.
# Note: pass the value explicitly (-e NAME=$VALUE) — `-e NAME` alone would
# rely on docker forwarding NAME from its own env, but the shell variable
# here is not exported, so the container would get an empty/missing value.
echo "[bootstrap] Generating dashboard auth hash…"
HASH="$(docker run --rm \
  -e "DASH_PASSWORD=$DASH_PASSWORD" \
  --entrypoint /opt/hermes/.venv/bin/python \
  "$IMAGE" -c "import os; from plugins.dashboard_auth.basic import hash_password; print(hash_password(os.environ['DASH_PASSWORD']))")"

# Write config.yaml into the volume via a throwaway helper container.
# The YAML is generated on the host (secrets expanded by the shell) into a
# temp file, then copied into the mounted volume — so the container itself
# never needs to know the plaintext password.
tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT
cat > "$tmp" <<YAML
# Generated by scripts/bootstrap-hermes-config.sh on $(date -u +%FT%TZ).
# This is the Hermes-managed config — edit it via the dashboard afterwards.
_config_version: 12

# Pick your model/provider in the dashboard (or uncomment and adjust here):
# model:
#   provider: openrouter
#   default: anthropic/claude-sonnet-4.6

# "all" enables every bundled tool, incl. the terminal tool (docker access).
toolsets:
  - all

dashboard:
  basic_auth:
    username: "$DASH_USERNAME"
    password_hash: "$HASH"
  public_url: $PUBLIC_URL
YAML

echo "[bootstrap] Writing config to $HERMES_VOLUME:/opt/data/config.yaml"
docker run --rm \
  -v "$HERMES_VOLUME:$MOUNT" \
  -v "$tmp:/tmp/config.yaml:ro" \
  --entrypoint /bin/sh \
  "$IMAGE" -c 'cat > /opt/data/config.yaml < /tmp/config.yaml'

echo "[bootstrap] Done."
