#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────
# bootstrap-hermes-config.sh
#
# Idempotent first-run bootstrap for the Hermes agent's config.yaml.
#
# - Runs on the VPS during deploy, wrapped in `doppler run` so secrets are
#   injected from Doppler (DASHBOARD_USERNAME / DASHBOARD_PASSWORD).
# - If config.yaml already exists and is valid (`_config_version` present),
#   it is left completely alone — the dashboard owns it from then on.
# - Otherwise it writes a minimal valid config (dashboard basic auth +
#   `_config_version: 12`), so the dashboard can start on first boot with
#   zero manual SSH. No `hermes setup` wizard required.
#
# Secrets used (from Doppler):
#   DASHBOARD_USERNAME   (default: admin)
#   DASHBOARD_PASSWORD   (required — used to derive the auth hash)
# ─────────────────────────────────────────────────────────────────────────

set -euo pipefail

HERMES_HOME="${1:?usage: bootstrap-hermes-config.sh <hermes-home>}"
CONFIG="$HERMES_HOME/config.yaml"
IMAGE="nousresearch/hermes-agent:latest"

DASH_USERNAME="${DASHBOARD_USERNAME:-admin}"
DASH_PASSWORD="${DASHBOARD_PASSWORD:-}"

mkdir -p "$HERMES_HOME"

# Already provisioned? Never touch it — the dashboard owns config from here.
if [ -f "$CONFIG" ] && grep -q '_config_version' "$CONFIG"; then
  echo "[bootstrap] $CONFIG already provisioned — leaving untouched."
  exit 0
fi

if [ -z "$DASH_PASSWORD" ]; then
  echo "[bootstrap] ERROR: DASHBOARD_PASSWORD is not set in Doppler. Cannot configure dashboard auth." >&2
  exit 1
fi

# Preserve any existing (e.g. stale pre-v12) config for reference.
if [ -f "$CONFIG" ]; then
  cp "$CONFIG" "$CONFIG.bak-$(date +%s)"
  echo "[bootstrap] Backed up existing config to $CONFIG.bak-*"
fi

# Derive the auth hash using the Hermes image's own helper.
# The password travels via env, never on the command line.
echo "[bootstrap] Generating dashboard auth hash…"
HASH="$(docker run --rm \
  -e DASH_PASSWORD \
  --entrypoint /opt/hermes/.venv/bin/python \
  "$IMAGE" -c "import os; from plugins.dashboard_auth.basic import hash_password; print(hash_password(os.environ['DASH_PASSWORD']))")"

cat > "$CONFIG" <<YAML
# Generated by scripts/bootstrap-hermes-config.sh on $(date -u +%FT%TZ).
# This is the Hermes-managed config — edit it via the dashboard afterwards.
_config_version: 12

# Pick your model/provider in the dashboard (or uncomment and adjust here):
# model:
#   provider: openrouter
#   default: anthropic/claude-sonnet-4.6

# "all" enables every bundled tool, incl. the terminal tool (docker access).
toolsets:
  - all

dashboard:
  basic_auth:
    username: "$DASH_USERNAME"
    password_hash: "$HASH"
  public_url: https://zeno.varunrs.in
YAML

echo "[bootstrap] Wrote $CONFIG"
